### ISSUE TITLE
Post reactions

### ISSUE THREAD

**Issue by claell** [linkedin-developers/linkedin-api-python-client#50]
I know this is not the right place to ask, but do you know by chance, whether there is an API product for LinkedIn that supports reactions to posts?

**Comment by shimizust** [comment]
Hi @claell , in general you can try searching the LinkedIn API docs for features. Otherwise the best place for this type of info is by raising a support request here: https://linkedin.zendesk.com/hc/en-us

But just fyi, this page talks about the reactions API available through the Community Management product: https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/shares/reactions-api?view=li-lms-2023-10&tabs=http

**Comment by claell** [comment]
Ah, great! Thanks for letting me know, and sorry for misusing this issue tracker for that.
